name: Multigames
main: xyz.rainbowpunk.multigames.Multigames
version: 0.0.1
api-version: 1.16
commands:
  color:
    description: Test out some colored text! You're going to have to provide the formatting, though.
  parkour:
    description: Starts the parkour challenge.
  uniqueitem:
    description: Get a unique item from this plugin!
  mystery:
    description: I know exactly what this command does, but I'm not gonna tell you what it is!
    usage: Your loss.
  dissolve:
    description: Dissolves your inventory! Entirely irreversable!
  stage:
    description: Allows you to start certain stages of the competition.