name: Multigames
main: xyz.rainbowpunk.multigames.Multigames
version: 0.0.1
api-version: 1.16
commands:
  color:
    description: Test out some colored text! You're going to have to provide the formatting, though.
  customitems:
    description: There are items unique to Multigames. Use this command to view and obtain them.
  parkour:
    description: Starts the parkour challenge.
  mystery:
    description: I know exactly what this command does, but I'm not gonna tell you!
    usage: Your loss.
  dissolve:
    description: Dissolves your inventory! Entirely irreversable!
  stage:
    description: Allows you to start certain stages of the competition.
  competition:
    description: Instantly join the competition!